export const ERROR_CODES = {
  EMPTY_INPUT: "EMPTY_INPUT",
  INPUT_TOO_LONG: "INPUT_TOO_LONG",
  LINK_INPUT_NOT_SUPPORTED: "LINK_INPUT_NOT_SUPPORTED",
  MODEL_TIMEOUT: "MODEL_TIMEOUT",
  MODEL_REFUSAL: "MODEL_REFUSAL",
  MODEL_ERROR: "MODEL_ERROR",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
